### ISSUE TITLE
clojure.instant: printable dates and reader related tests

### ISSUE THREAD

**Issue by jfacorro** [jfacorro/clojerl#262]

**Comment by bensu** [comment]
I have a working implementation of `clojure.instant/print-date` but I'm not sure how to hook it up to `clojure.core/print-method` since erlang dates are untagged tuples. How would you recommend dispatching to date from the tuple?

I see three possible paths:

1. Don't integrate dates into the standard printer.
2. Use `deftype` with a custom date type for this platform and add `from-erlang`/`to-erlang` functions.
3. Copy [Elixir's representation of dates](https://hexdocs.pm/elixir/Date.html) so that at least Elixir's functions work over them.

**Comment by jfacorro** [comment]
I lean towards option 2. I have mixed feelings about using `deftype` since so far all "primitive" types have been implemented in Erlang, but on the other hand ClojureScript does use `deftype` and another advantage is that there would be no need to update the implementation of dates if the underlying representation for types changes in Clojerl. 
 
For regular expressions the first approach was not to define a type for them and just have the reader return the result from `re:compile/1`, which is a tuple. But this meant that they couldn't participate in protocols or multi-methods (e.g. `clojure.core/print-method`), so the `erlang.util.Regex` type was created. This type wraps the compiled regex in a type, stores the original value and adapts some of the functions from the `re` module so that they return (Erlang) binaries instead of (Erlang) strings.

The current underlying representation for types in Clojerl is through Erlang records, I thought about using the same map representation that Elixir uses for structs but I thought it would be slower (just some premature optimization 😞). I now think it would be nice to try it out and compare the results when running the current basic benchmarks (`make benchmark`). When using maps for representing types I would prefer having a `__type__` key instead of a `__struct__` key though, this would mean no compatibility with Elixir, but I don't think that should be our focus. 

What do you think?

**Comment by bensu** [comment]
I agree with 2. I will look at `erlang.util.Regex` for comparison to see how to write the type. Do you suggest `erlang.util.Date` to mirror `java.util.Date`?

I don't have a good sense on the tradeoffs between maps and tuples for the type representation. I'll research the Elixir community to see how did that decision fare. In case you are interested in using maps, I would try to preserve Elixir's `__struct__` key. If might not be as nice but if that is the only cost to being compatible, it is a small price to pay.
