### ISSUE TITLE
Does Clojerl have emacs plugins?

### ISSUE THREAD

**Issue by damon-kwok** [jfacorro/clojerl#315]
Does Clojerl have emacs plugins?

**Comment by jfacorro** [comment]
@damon-kwok To edit files I currently use `clojure`, `paredit-mode` and `rainbow-delimiters-mode`  This project is in very early stages, so there is currently nothing like Clojure's `cider` or Erlang's `edts` modes.

**Comment by damon-kwok** [comment]
thanks
